#!/bin/bash

media_ids=()

for camera in lodge summit glory; do
  id=$(curl -H "Authorization: Bearer $MASTODON_TOKEN" -H "Content-Type: multipart/form-data" --silent -X POST https://nelson.social/api/v2/media --form file="@$camera.jpg" | jq .id --raw-output)
  media_ids+=("$id")
done

echo "${media_ids[@]}"
